# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://portal.cloud.hashicorp.com/vagrant/discover/kalilinux/rolling
# https://www.kali.org/blog/announcing-kali-for-vagrant/
# https://bugs.kali.org/view.php?id=7885


cluster = {
  "kali-soc-vagrant-vm"   => {
    :box => "kalilinux/rolling", :box_version => "2025.2.1",
    :cpus => 4, :mem => 8192,
    :ip => "172.26.10.11",
  },
  "debian-soc-vagrant-vm" => {
    :box => "generic/debian12",
    :cpus => 2, :mem => 4096,
    :ip => "172.26.10.12",
  },
}
groups = {
  "remote" => cluster.keys,
  "kali" => ["kali-soc-vagrant-vm"],
  "servers" => ["debian-soc-vagrant-vm"],
}

Vagrant.configure("2") do |config|
  cluster.each do |name, data|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define name do |host|
      host.vm.box = data[:box]
      host.vm.box_version = data[:box_version] if data[:box_version]
      host.vm.hostname = name
      # host.vm.network "public_network", ip: data[:ip], bridge: "enp4s0"
      host.vm.network "private_network", ip: data[:ip]
      host.vm.provider :virtualbox do |vb, override|
        vb.cpus = data[:cpus]
        vb.memory = data[:mem]
        if groups["kali"].include?(name)
          vb.gui = true
          vb.customize ["modifyvm", :id, "--vram", "128"]
          vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        end
      end
      if groups["kali"].include?(name)
        host.vm.synced_folder "../kali", "/lab"
      elsif groups["servers"].include?(name)
        host.vm.synced_folder "../server", "/lab"
      end
    end
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
  # SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yaml"
    ansible.groups = groups
  end
end
