---

- name: Install key packages
  apt:
    update_cache: yes
    name:
      - bat
      - eza
      # - docker.io
      # - docker-compose
      - fzf
      - git-delta
      - jq
      - lf
      - ripgrep
      - tmux
    state: present

- name: Create bat symlink
  file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    state: link
    force: no

# - name: Add vagrant user to docker group
#   user:
#     name: vagrant
#     groups: docker
#     state: present
