---

- name: Tweak zsh prompt (single line)
  replace:
    path: /home/vagrant/.zshrc
    regexp: '^PROMPT_ALTERNATIVE=twoline'
    replace: 'PROMPT_ALTERNATIVE=oneline'

- name: Tweak zsh prompt (no newline)
  replace:
    path: /home/vagrant/.zshrc
    regexp: '^NEWLINE_BEFORE_PROMPT=yes'
    replace: 'NEWLINE_BEFORE_PROMPT=no'

- name: Create kali-aliases.zsh file
  copy:
    dest: /home/vagrant/kali-aliases.zsh
    content: |
      ts () {
        if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]]
        then
          tmux new-session "$@"
        else
          tmux new-session -s "$@"
        fi
      }

      tn () {
        tmux new -s $(pwd | sed 's#.*/##')
      }
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Append kali-aliases.zsh source to .zshrc
  blockinfile:
    path: /home/vagrant/.zshrc
    block: |
      # Custom Kali ZSH config
      source ~/kali-aliases.zsh
    marker: "{mark}"
    marker_begin: "\n# BEGIN ANSIBLE MANAGED BLOCK - Custom ZSH aliases"
    marker_end: "# END ANSIBLE MANAGED BLOCK - Custom ZSH aliases"
    state: present
