---

- name: Tweak zsh prompt (single line)
  replace:
    path: /home/vagrant/.zshrc
    regexp: '^PROMPT_ALTERNATIVE=twoline'
    replace: 'PROMPT_ALTERNATIVE=oneline'

- name: Tweak zsh prompt (no newline)
  replace:
    path: /home/vagrant/.zshrc
    regexp: '^NEWLINE_BEFORE_PROMPT=yes'
    replace: 'NEWLINE_BEFORE_PROMPT=no'

- name: Create kali-aliases.zsh file
  copy:
    dest: /home/vagrant/kali-aliases.zsh
    content: |
      ts () {
        if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]]
        then
          tmux new-session "$@"
        else
          tmux new-session -s "$@"
        fi
      }

      tn () {
        tmux new -s $(pwd | sed 's#.*/##')
      }

      alias dps="docker ps"
      alias dcdd='docker compose down --rmi local -v --remove-orphans'
      alias dcd="docker compose down"
      alias dcu="docker compose up"
      alias dcl="docker compose logs"
      alias dcd="docker compose stop"
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Append kali-aliases.zsh source to .zshrc
  lineinfile:
    path: /home/vagrant/.zshrc
    line: 'source ~/kali-aliases.zsh'
    state: present
    create: no
